<a href="https://colab.research.google.com/github/Shawnpeter578/practise_ML/blob/main/spam_email_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('/content/spam.csv')
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [2]:
len(df)

5572

In [4]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [5]:
df['spam'] = df.Category.apply(lambda x:1 if x=="spam" else 0)

In [9]:
df

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.Message, df.spam, test_size=0.25)

In [12]:
x_train

2642    You are guaranteed the latest Nokia Phone, a 4...
3900    Ü mean it's confirmed... I tot they juz say on...
2967                         Are you being good, baby? :)
5426        Oh yeah! And my diet just flew out the window
3443    Save money on wedding lingerie at www.bridal.p...
                              ...
1834                             When should I come over?
3252                          I‘ll leave around four, ok?
3129    would u fuckin believe it they didnt know i ha...
3425    Am new 2 club & dont fink we met yet Will B gr...
3553                            Lol u still feeling sick?
Name: Message, Length: 4179, dtype: object

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(x_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [16]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [17]:
emails_count = v.transform(emails)
emails_count

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 22 stored elements and shape (2, 7453)>

In [19]:
model.predict(emails_count)

array([0, 1])

In [20]:
x_test_count = v.transform(x_test)
model.score(x_test_count, y_test)

0.9870782483847811

In [21]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [22]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [23]:
clf.score(x_test, y_test)

0.9870782483847811

In [24]:
clf.predict(emails)

array([0, 1])